{
  "name": "ipl-auction-backend",
  "type": "web",
  "env": "node",
  "buildCommand": "npm install",
  "startCommand": "npm start",
  "envVars": [
    {
      "key": "MONGO_URI",
      "value": ""
    },
    {
      "key": "NODE_ENV",
      "value": "production"
    },
    {
      "key": "FRONTEND_URL",
      "value": ""
    }
  ]
}
